src/Dummy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls' , namespace='shop')),
    path('account/',include('accounts.urls', namespace='accounts')),
    path('final/cart/', include('cart.urls',namespace='cart')),

]

src/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('signup/',views.Register.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(),name='login') ,
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    ]

src/cart/urls.py
from django.urls import path
from . import views

app_name= 'cart'

urlpatterns = [

    path('', views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),

]

src/shop/urls.py
from django.contrib import admin
from . import views

from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [


    path('',views.index,name='index'),
    path('cart/',views.cart,name='cart'),
    path('<slug:slug>/', views.categories, name='category'),
    path('<slug:slug>/<int:id>/', views.product_detail, name='product_detail'),
    path('search/results/', views.search , name='search')



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models

# Create your models here.

src/cart/models.py
from django.db import models

# Create your models here.

src/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):

   name =  models.CharField(max_length=30,db_index=True)
   slug = models.SlugField(max_length=50,db_index=True,unique=True)

   class Meta:

      ordering=('name',)
      verbose_name='Category'
      verbose_name_plural = 'Catigories'

   def __str__(self):
       return self.name


class Product(models.Model):
   category = models.ForeignKey(Category,on_delete=None)
   name = models.CharField(max_length=30,db_index=True)
   slug = models.SlugField(max_length=50, db_index=True, unique=True)
   image = models.ImageField(blank=True,upload_to='static/products')
   descp = models.TextField(blank=True)
   stock = models.PositiveIntegerField()
   price = models.DecimalField(max_digits=10,decimal_places=2)
   avilable = models.BooleanField(default=True)
   featured = models.BooleanField(default=False)
   special = models.BooleanField(default=False)
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)

   class Meta:
      verbose_name = 'Product'
      verbose_name_plural  = 'Products'

   def __str__(self):
       return self.name

   def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug, self.id])

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProduct(forms.Form):

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

src/shop/forms.py
from django import forms

class Contact(forms.Form):

    name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}))
    email = forms.EmailField(max_length=50,widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}))
    message = forms.CharField(required=True,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Message','row':'5'}))

src/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.

class Register(CreateView):

    template_name = 'register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('shop:index')

src/cart/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProduct
# Create your views here.
@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProduct(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:cart_detail')

def cart_remove(request,product_id):

    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProduct(
            initial={'quantity': item['quantity'],
                     'update': True})
    return render(request,'detail.html',{'cart': cart})

src/shop/views.py
from django.shortcuts import render ,get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from .forms import Contact
from django.core.mail import send_mail
from .models import Product , Category
from cart.forms import CartAddProduct


# Create your views here.


def index(request):

    if request.method == 'POST':
        form = Contact(request.POST)
        if form.is_valid():
            # send email code goes here
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']

            message = "{0} has sent you a new message:\n\n{1}".format(sender_name, form.cleaned_data['message'])
            send_mail('New Enquiry', message, sender_email, ['deva4rf@gmail.com'])
            return HttpResponse('Thanks for contacting us!')
    else:
        form = Contact()

    men = Product.objects.filter(category_id=1).filter(featured=True)
    women = Product.objects.filter(category_id=2).filter(featured=True)
    kids = Product.objects.filter(category_id=3).filter(featured=True)
    acc = Product.objects.filter(category_id=4).filter(featured=True)
    special = Product.objects.filter(special=True)

    context = {
        'form': form,
        'men':men,
        'women':women,
        'kids' : kids,
        'acc':acc,
        'special':special,
        'cart_product_form': CartAddProduct()



    }


    return render(request,'index.html',context)


def cart(request):
    return render(request,'cart.html',{})

def categories(request,slug=None):

    categories = Category.objects.all()
    products = Product.objects.filter(avilable=True)
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'cart_product_form': CartAddProduct()
    }
    return render(request, 'cat.html', context)


def product_detail(request, slug , id):


    product = get_object_or_404(Product, id=id, slug=slug , avilable=True)

    context = {
        'product': product,
        'cart_product_form' : CartAddProduct()
    }


    return render(request,'details.html',context)
def search(request):

    query = request.GET.get('q')

    product = Product.objects.filter(

                                      Q(name__icontains=query) |
                                      Q(descp__icontains=query)

                                      )

    context = {
        'query' :query ,
        'cart_product_form': CartAddProduct(),
        'product': product
    }

    return render(request,'results.html',context)

src/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

    <link rel="icon" type="image/ico" href="{% static 'images/download.png' %}"/>
    <title>
    {% block title %}
    DUMMY
    {% endblock %}
    </title>


</head>

<body>

<!-- navbar -->

      <div class="container-fluid">
        <nav class="navbar navbar-light text-light d-flex justify-content-center justify-content-lg-between">

                <a href="{% url 'shop:index' %}" class="navbar-brand">

                    <h5 class="text-dark"><strong><img src="{% static 'images/download.png' %}" class="mr-1">DUMMY</strong></h5>

                </a>

                <form class="searchbar" method="GET" action="{% url 'shop:search' %}">
                  <div class="input-group mb-3 mb-lg-0 ">
                          <input type="text" class="form-control" placeholder="Search" name="q" value="{{request.GET.q}}">
                      <div class="input-group-append">
                          <span class="input-group-text search">
                              <button class="btn btn-sm text-light"><i class="fas fa-search"> </i></button>
                          </span>
                      </div>
                  </div>
                   

              </form>

            {% if user.is_authenticated %}
            <div class="">
                <form method="post" action="{% url 'accounts:logout' %}" class="mylogout">

                    <input type="submit" value="logout" class="mybutton btn btn-dark links">
                    {% csrf_token %}

                </form>
            {% else %}

                        <div>
                         <a href="{%url 'accounts:signup' %}" class="btn btn-warning links">Sign Up</a>
                         <a href="{%url 'accounts:login' %}" class="btn btn-warning ml-2 links">Sign IN</a>

                         <a href="{% url 'cart:cart_detail' %}" class="cart"><i class="fas fa-cart-plus ml-2 icon mr-1"></i><strong class="text-dark">Cart</strong></a>
                        </div>
                        </div>
            {% endif %}
             </nav>
          </div>


            <section id="icons" class="category">
                    <div class="container text-center ">

                        <div class="row">
                            <div class="col-md-3 p-3">
                                <a id="category" href="/men" class="text-dark btn "><strong>MEN</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/kids" class="text-dark btn  "><strong>KIDS</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/accessories" class="text-dark btn  "><strong>ACCESSORIES</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/women" class="text-dark btn  "><strong>WOMEN</strong></a>
                            </div>
                        </div>
                    </div>
                </section>

    {% block body %}
    DUMMY
    {% endblock %}

                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"  crossorigin="anonymous">
                </script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"  crossorigin="anonymous">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous">
                </script>
                <script src="{% static 'js/javascript.js' %}"></script>
                
                
</body>

</html>

src/accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
SignUp
{% endblock %}

{% block body %}
<div class="container mt-4 myform">
        <div class="row mt-5">
                <div class="col-md-6 m-auto">
                  <div class="text-center">
                  <h1 class="text-center mb-3">
                    <i class="fas fa-user-plus"></i> Register
                  </h1>
                    </div>
                </div>
        </div>
    <form method="post">

        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Register" class="btn btn-warning btn-lg mybutton">

    </form>
</div>

{% endblock %}

src/cart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

     <link rel="icon" type="image/ico" href="{% static 'images/download.png' %}"/>
    <title>
    {% block title %}
    DUMMY
    {% endblock %}
    </title>


</head>

<body>

<!-- navbar -->

<div class="container-fluid">
    <nav class="navbar navbar-light text-light d-flex justify-content-center justify-content-lg-between">

            <a href="{% url 'shop:index' %}" class="navbar-brand">

                <h5 class="text-dark"><strong><img src="{% static 'images/download.png' %}" class="mr-1">DUMMY</strong></h5>

            </a>

            <form class="searchbar" method="GET" action="{% url 'shop:search' %}">
              <div class="input-group mb-3 mb-lg-0 ">
                      <input type="text" class="form-control" placeholder="Search" name="q" value="{{request.GET.q}}">
                  <div class="input-group-append">
                      <span class="input-group-text search">
                          <button class="btn btn-sm text-light"><i class="fas fa-search"> </i></button>
                      </span>
                  </div>
              </div>
               

          </form>

            {% if user.is_authenticated %}
            <div class="">
                <form method="post" action="{% url 'accounts:logout' %}" class="mylogout">

                    <input type="submit" value="logout" class="mybutton btn btn-warning links">
                    {% csrf_token %}

                </form>
            {% else %}

                        
                         <a href="{%url 'accounts:signup' %}" class="btn btn-warning links">Sign Up</a>
                         <a href="{%url 'accounts:login' %}" class="btn btn-warning ml-2 links">Sign IN</a>

                         <a href="{% url 'cart:cart_detail' %} "><i class="fas fa-cart-plus ml-2 icon "></i></a>
                        </div>
            {% endif %}
             </nav>
          </div>


            <section id="icons" class="category">
                    <div class="container text-center ">

                        <div class="row">
                            <div class="col-md-3 p-3">
                                <a id="category" href="/men" class="text-dark btn "><strong>MEN</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/kids" class="text-dark btn  "><strong>KIDS</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/accessories" class="text-dark btn  "><strong>ACCESSORIES</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/women" class="text-dark btn  "><strong>WOMEN</strong></a>
                            </div>
                        </div>
                    </div>
                </section>

    {% block body %}
    DUMMY
    {% endblock %}

                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"  crossorigin="anonymous">
                </script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"  crossorigin="anonymous">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous">
                </script>
                <script src="{% static 'js/javascript.js' %}"></script>
</body>

</html>

src/cart/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
Your shopping Cart
{% endblock %}

{% block body %}

{% if cart %}

<section class="buy">

              <div class="container mt-3">
                  <h3>Cart {{cart|length}} </h3>
                  <p class="mb-5">Your order is eligible for Free Shipping</p>

                  {% for item in cart %}
                    {% with product=item.product %}

                      <div class="row mt-3 shadow mb-5">
                            <div class="col-4">

                                    <img src="{{product.image.url}}" class="mb-4">

                                    <div class="happy">
                             <p class="h4 ml-1">{{product.name}}</p>
                             <p class="ml-1">{{product.descp}} </p>
                             
                             <p class="ml-1">Eligible for <strong>Free Shipping</strong></p>
                             <span class="rating ml-1"><i class="fas fa-star">

                             </i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>


                            </div>
                            </div>




                            <div class="col-2">
                                    <div class="form-group">
                                            <label for="inputState" class="h6 mb-1"><strong>Quantity</strong></label>
                                            <p id="inputState" >

                                             <form action="{% url 'cart:cart_add' product.id %}" method="post" class="mylabel1">
                                            {{ item.update_quantity_form.quantity }}
                                            {{ item.update_quantity_form.update }}
                                            
                                            <input type="submit" value="Update" class="btn btn-warning  btn-sm  mt-2">
                                            {% csrf_token %}
                                          </form>

                                            </p>

                                          </div>
                            </div>
                            <div class="col-2">
                              <p class="h6 mb-4">
                                <strong> Unit Price</strong>
                              </p>
                              <p class="prices">{{product.price}}</p>
                            </div>
                            <div class="col-2">
                                    <p class="h6 mb-4">
                                      <strong>Sub Total</strong>
                                    </p>
                                    <p class="prices">{{item.total_price}}</p>
                                    
                            </div>
                            
                            <div class="text-right col-2">
                               <br>
                                <br>
                                <br>
                                <br>
                              <a href='{% url "cart:cart_remove" product.id%}' class="btn btn-dark btn-sm">Delete</a>
                            </div>
                          </div>
                      {% endwith %}
{% endfor %}
                  </div>


          </section>

          <section>
              <div class="container">
                  <p class="h3 text-right shadow">
                      Total : <span class="text-dark"><strong>{{cart.get_total_price}} $</strong></span>
                  </p>
              </div>
          </section>

{% else %}

<h3>No products till now </h3>


{% endif %}



{% endblock %}

<!--

--}

src/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

     <link rel="icon" type="image/ico" href="{% static 'images/download.png' %}"/>
    <title>
    {% block title %}
    DUMMY
    {% endblock %}
    </title>


</head>

<body>

<!-- navbar -->

<div class="container-fluid">
    <nav class="navbar navbar-light text-light d-flex justify-content-center justify-content-lg-between">

            <a href="{% url 'shop:index' %}" class="navbar-brand">

                <h5 class="text-dark"><strong><img src="{% static 'images/download.png' %}" class="mr-1">DUMMY</strong></h5>

            </a>

            <form class="searchbar" method="GET" action="{% url 'shop:search' %}">
              <div class="input-group mb-3 mb-lg-0 ">
                      <input type="text" class="form-control" placeholder="Search" name="q" value="{{request.GET.q}}">
                  <div class="input-group-append">
                      <span class="input-group-text search">
                          <button class="btn btn-sm text-light"><i class="fas fa-search"> </i></button>
                      </span>
                  </div>
              </div>
               

          </form>
          
            {% if user.is_authenticated %}
            <div class="">
                <form method="post" action="{% url 'accounts:logout' %}" class="mylogout">

                    <input type="submit" value="logout" class="mybutton btn btn-warning links">
                    {% csrf_token %}

                </form>
            {% else %}

                        
                         <a href="{%url 'accounts:signup' %}" class="btn btn-warning links">Sign Up</a>
                         <a href="{%url 'accounts:login' %}" class="btn btn-warning ml-2 links">Sign IN</a>

                         <a href="{% url 'cart:cart_detail' %} "><i class="fas fa-cart-plus ml-2 icon "></i></a>
                        </div>
            {% endif %}
             </nav>
          </div>


            <section id="icons" class="category">
                    <div class="container text-center ">

                        <div class="row">
                            <div class="col-md-3 p-3">
                                <a id="category" href="/men" class="text-dark btn "><strong>MEN</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/kids" class="text-dark btn  "><strong>KIDS</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/accessories" class="text-dark btn  "><strong>ACCESSORIES</strong></a>
                            </div>
                            <div class="col-md-3 p-3">
                                    <a id="category" href="/women" class="text-dark btn  "><strong>WOMEN</strong></a>
                            </div>
                        </div>
                    </div>
                </section>

    {% block body %}
    DUMMY
    {% endblock %}

                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"  crossorigin="anonymous">
                </script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"  crossorigin="anonymous">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous">
                </script>
                <script src="{% static 'js/javascript.js' %}"></script>
</body>

</html>

src/shop/templates/cat.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
{{category}}
{% endblock %}

{% block body %}



          
                        

    <div class="container-fluid">
        <div class="row">
           

            <div class="col notfixe">


        <section class="offers">
                <div class="container mt-5">

                    <h3 class="mb-5"> <span id="prettyone" ><i class="fas fa-tshirt mr-2 text-dark"></i></span>{{category}} Products </h3>
                   
                    <div class="row ">

                        {% for item in products %}
                                <div class="col-3">
                                <div class="card mb-5 shadow">
                                  <img src="{{item.image.url}}" class="card-img-top" alt="...">
                                  <div class="card-body">
                                    <h5 class="card-title"> <a href="{{item.get_absolute_url}}" class="text-dark h5 mylink1 nav-link p-0 "><strong>{{item.name}} </strong></a> </h5>
                                    <p class="mt-4">{{item.price}}</p>

                                    <span class="rating">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                    </span>

                                    <p class="text-center">

                                      <form method="post"  action="{% url 'cart:cart_add' item.id %}" class="mylabel1">

                                          {{cart_product_form}}
                                          {% csrf_token %}


                                          <div><i class="fas fa-plus mylink1 text-info"></i>
                                            <input type="submit" value="Add To Cart" class="btn btn-link text-info mylink nav-link d-inline"></div>



                                      </form>


                                 

                                    </p>
                                  </div>


                        </div>
                    </div>
                        {% endfor %}
                    
                    </div>
                </div>
        </section>

        
           {% endblock %}

src/shop/templates/details.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{product.name}}
{% endblock  %}

     {% block body %}


<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col mt-3 mr-3">
          <img src="{{product.image.url}}" class="product justify-content-left">
        </div>
        <div class="col mr-3">
            <h3 class="text-warning "><strong>{{product.price}}</strong></h3>
            
            
            <p class="text-muted hm">By H&M</p>
            <span class="rating1"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
            <p class="hi5 mb-4">Eligible for <strong>Free Shipping</strong></p>
            <hr>
            <p class="hi5 mt-4"><strong>Describtion :</strong></p>
            <p class="hi5 text-muted mb-2">Product Features :</p>

            <p class="hi6">Brand : H&M</p>
            <p class="hi6">Size : xl</p>
            <p class="hi6">Color : All Colors</p>
            <p class="hi6">Targeted Groub : All</p>
            <p class="hi6">Product status : Aviliable</p>
            <p class="hi6">Marketing by : Dummy</p>


        </div>

        <div class="col text-center">
            <h4 class="mb-3"><strong>{{product.name}}</strong></h4>
            <p class="hi5" >Ship to <strong>Egypt</strong></p>
            <p>Get It <strong>Tomorrow</strong> </p>
            <form method="post"  action="{% url 'cart:cart_add' product.id %}" class="mylabel1">

                {{cart_product_form}}
                {% csrf_token %}
                                                   <p class="text-center">


                                   <input type="submit" value="Add To Cart" class="btn btn-dark text-center btn-lg hello mt-4 w-100">

          </p>



            </form>
        </div>
        </div>
        </div>
      </div>
  </div>

{% endblock %}

src/shop/templates/results.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
You have searched for {{query}}
{% endblock  %}

     {% block body %}



         <section class="offers">

                <div class="container mt-5">

                    <div class="row">

                        {% for item in product %}

                                <div class="col-4">
                                    <div class="card mb-3 shadow">
                                  <img src="{{item.image.url}}" class="card-img-top" alt="...">
                                  <div class="card-body">
                                    <h5 class="card-title"> <a href="{{item.get_absolute_url}}" class="text-dark h5 mylink1 nav-link p-0 "><strong>{{item.name}}</strong> </a> </h5>
                                    <p class="mt-4">{{item.price}}</p>

                                    <span class="rating">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                    </span>

                                    <p class="text-center">
                                      <form method="post"  action="{% url 'cart:cart_add' item.id %}" class="mylabel1">

                                          {{cart_product_form}}
                                          {% csrf_token %}


                                          <div><i class="fas fa-plus mylink1 text-info"></i>
                                            <input type="submit" value="Add To Cart" class="btn btn-link text-info mylink nav-link d-inline"></div>


                                      </form>


                                   

                                    </p>
                                </div>
                                  </div>


                        </div>

                        {% endfor %}

                    </div>
                </div>
        </section>


    {% endblock %}}